### ISSUE TITLE
build error with mruby-mrbgem-template

### ISSUE THREAD

**Issue by yamori813** [matsumotory/mruby-simplehttp#13]
mruby-mrbgem-templateと一緒にビルドするとビルドエラーが発生します。

OSはFreeBSD 10.3Rです。

追加しているgemは以下になります。

  conf.gem :git => 'https://github.com/iij/mruby-pack.git'
  conf.gem :git => 'https://github.com/iij/mruby-digest.git'
  conf.gem :git => 'https://github.com/mattn/mruby-json.git'
  conf.gem :git => 'https://github.com/mattn/mruby-uv.git'
  conf.gem :git => 'https://github.com/mattn/mruby-http.git'
  conf.gem :git => 'https://github.com/matsumoto-r/mruby-simplehttp.git'
  conf.gem :git => 'https://github.com/matsumoto-r/mruby-httprequest.git'
  conf.gem :git => 'https://github.com/matsumoto-r/mruby-mrbgem-template.git'

エラーメッセージ

microserver % make
ruby ./minirake
(in /storage/home/hiroki/opensource/mruby-1.2.0)
LD    build/host/bin/mirb 
/storage/home/hiroki/opensource/mruby-1.2.0/build/host/lib/libmruby.a(gem_init.o
): In function `mrb_init_mrbgems':
/storage/home/hiroki/opensource/mruby-1.2.0/build/host/mrbgems/gem_init.c:122: u
ndefined reference to `GENERATED_TMP_mrb_mruby_sprintf_gem_init'
/storage/home/hiroki/opensource/mruby-1.2.0/build/host/lib/libmruby.a(gem_init.o
): In function `mrb_final_mrbgems':
/storage/home/hiroki/opensource/mruby-1.2.0/build/host/mrbgems/gem_init.c:84: un
defined reference to `GENERATED_TMP_mrb_mruby_sprintf_gem_final'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/storage/home/hiroki/opensource/mruby-1.2.0/build/host/lib/libmruby.a(gem_init.o
): In function `mrb_init_mrbgems':
/storage/home/hiroki/opensource/mruby-1.2.0/build/host/mrbgems/gem_init.c:122: u
ndefined reference to `GENERATED_TMP_mrb_mruby_sprintf_gem_init'
/storage/home/hiroki/opensource/mruby-1.2.0/build/host/lib/libmruby.a(gem_init.o
): In function `mrb_final_mrbgems':
/storage/home/hiroki/opensource/mruby-1.2.0/build/host/mrbgems/gem_init.c:84: un
defined reference to `GENERATED_TMP_mrb_mruby_sprintf_gem_final'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command Failed: [clang -L"/storage/home/hiroki/opensource/mruby-1.2.0/build/host
/mrbgems/mruby-uv/libuv-1.0.0/.libs" -o "/storage/home/hiroki/opensource/mruby-1
.2.0/build/host/bin/mirb" "/storage/home/hiroki/opensource/mruby-1.2.0/build/hos
t/mrbgems/mruby-bin-mirb/tools/mirb/mirb.o" "/storage/home/hiroki/opensource/mru
by-1.2.0/build/host/lib/libmruby.a"  -lm -lreadline -lncurses -lcrypto -luv -lpt
hread -lrt -lm -lkvm ]
Rakefile:70:in `block (4 levels) in <top (required)>'
*** Error code 1

Stop.

**Comment by matsumotory** [comment]
手元のLinuxで試した所、特に問題なく動きますね。ログを見る限りは何かのmrbgemの依存がmrubyのrakeのtaskで解決できていない可能性があるので、mruby本体のtaskの問題かもしれません。

**Comment by udzura** [comment]
* microserver? のディレクトリ構成がどうなっているか
* mrubyのバージョン/commitishは何か
* mruby自体で一度 `rake clean(make deep_clean)` を実施してやり直しをするとどうなるか

と言った情報があると解明が進むかもしれない、と思いました。

**Comment by yamori813** [comment]
mrubyは1.2.0のリリースのソースを使っていてホストおよびターゲットともamd64で確認していました。

make cleanを実行後にmakeしたところ問題起きなくなりました。

お手数おかけしてすみませんでした。
