### ISSUE TITLE
How can I send File?

### ISSUE THREAD

**Issue by nsheremet** [matsumotory/mruby-simplehttp#14]
Hi!
Its not a real Issue, but I have one question.
I need to send a file with `"Content-Type" => "multipart/form-data"`, using your mruby-gem `mruby-simplehttp` or `mruby-httprequest`. But I dont understand how I can do this. Can you help me with this?

Thank you for this two awesome mruby-gems!

**Comment by nsheremet** [comment]
Ok, thanks, I make a PR for easy file sending

**Comment by matsumotory** [comment]
Oh, sorry for my late response. mruby-simplehttp don't support file sending. So Could you send the PR?
