### ISSUE TITLE
POST request with a large body blocks forever

### ISSUE THREAD

**Issue by genya0407** [matsumotory/mruby-simplehttp#23]
When I send a POST request having a large body (say, 1MB) with `SimpleHttp#post`, it blocks forever and never responds.

I found that `PolarSSL::SSL#read` [here](https://github.com/matsumotory/mruby-simplehttp/blob/master/mrblib/simplehttp.rb#L127) blocks.

I guess that `PolarSSL::SSL#write` [here](https://github.com/matsumotory/mruby-simplehttp/blob/master/mrblib/simplehttp.rb#L126) breaks the socket because `request_header` is larger than socket's write buffer size.
In fact, after I modified `ssl.write` to the following code, it responds correctly.

```ruby
...
ssl.handshake
# ssl.write request_header
request_header.each_char.each_slice(BUF_SIZE.to_i) do |chars|
  ssl.write chars.join
end
while chunk = ssl.read(BUF_SIZE.to_i)
...
```

If the above modification is O.K., I am willing to work on this issue (although there may be a more efficient way to slice string).

**Comment by matsumotory** [comment]
@genya0407 Thank you for your report. Sorry for my late response. I think your proposal is good. So could you send us the PR?
