### ISSUE TITLE
Stop testing on old mruby, and start testing on new mruby

### ISSUE THREAD

**Issue by genya0407** [matsumotory/mruby-simplehttp#25]
Currently, mruby 1.3.0 and 1.4.1 are tested in `.travis.yml`.

However, on mruby 1.3.0, the test fails because `mruby-shelf`'s test fails.
https://travis-ci.org/github/genya0407/mruby-simplehttp/jobs/762701681

FYI: `mruby-shelf` seems to support only current stable mruby version.
https://github.com/katzer/mruby-shelf/blob/master/.travis.yml#L30

In addition, there are new stable versions of mruby (2.1.x, 3.0.x).
Testing on them will be useful.

So, I propose:

- remove 1.3.0 from .travis.yml
- add 2.1.x and 3.0.x to .travis.yml

**Comment by matsumotory** [comment]
We agree with you. Could you create the PR about this issue?
